#!/usr/bin/env bash
# Installs nginx on web-01 server
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
