#!/usr/bin/env bash
# Installs nginx on web-01 server
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
