#!/usr/bin/env bash
# configures web-02 to be identical to web-01
apt -y update
apt -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen \[::\]:80 default_server;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sed -i '/error_page 404 \/custom_404.html;/a location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
sed -i "/listen \[::\]:80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
