#!/usr/bin/env bash
# Installs and configure HAproxy on your lb-01 server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "
frontend lb
bind *:80
mode http
default_backend servers	
backend servers
mode http
balance roundrobin
server 876-web-01 35.196.198.147:80 check
server 876-web-02 35.229.66.46:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
