#!/usr/bin/env bash
# Script loops from 1 to 10
# displays "bad luck" for 4th loop iteration
# displays "good luck" for 8th loop iteration
# displays "Holberton School" for the other iterations
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School" 
	fi
	(( i++ ))
done
