#!/usr/bin/env bash
# configures an Ubuntu server
egrep -v "localhost|facebook.com" /etc/hosts > hosts.tmp
echo '127.0.0.2 localhost' >> hosts.tmp
echo '8.8.8.8 facebook.com' >> hosts.tmp
cp -f hosts.tmp /etc/hosts
rm hosts.tmp
